### ISSUE TITLE
how to customize my own network

### ISSUE THREAD

**Issue by Yoonhee-Gil** [knowledgedefinednetworking/demo-routenet#1]
Hello, I'm a student who's been working with your paper "Unveiling the potential of GNN~". I've done some experiments with the datasets you uploaded, but I want to know how those datasets are made. I want to test your code to my own network but I can't get hold of how it was made. It seems that omnetpp does not support your dataset type. So it'd be great if you also upload how you made your datasets.

**Comment by jsuarezv** [comment]
Dear Yoonhee,
The simulator code is not open source yet and we do not plan to release it in the short-term. However, we will let you know as soon as we make it public.

We plan to release soon new datasets including new features such as variable queue sizes on forwarding nodes. You can subscribe to the mailing list kdn-users@knowledgedefinednetworking.org (Link: https://mail.knowledgedefinednetworking.org/cgi-bin/mailman/listinfo/kdn-users) to receive timely updates with new dataset releases.

Regards,
José
