### ISSUE TITLE
How to predict jitter and packet loss ratio?

### ISSUE THREAD

**Issue by ZoeJiang2222** [knowledgedefinednetworking/demo-routenet#22]
Hello, 
it seems like that I don't understand how to  predict jitter and packet loss ratio,I just have tried to replace “delay” with "jitter" in the definition of "target",and I didn't modify anywhere else,the result is too strange to tolerate. So I think there's propably something wrong .

If I want to predict jitter and packet loss ratio with your jupyter notebook,where should I modify?Could you please just tell me how to do?
Thank  you very much.

**Comment by paulalmasan** [comment]
Hi! In the parse() function (https://github.com/knowledgedefinednetworking/demo-routenet/blob/6fe560081f805c8fc468567b6f30b3d923a00303/code/routenet_with_link_cap.py#L64) try changing the target="delay" to traget="jitter". Notice that you will have to add an 'if' to normalize the jitte labels like in https://github.com/knowledgedefinednetworking/demo-routenet/blob/6fe560081f805c8fc468567b6f30b3d923a00303/code/routenet_with_link_cap.py#L85.

**Comment by ZoeJiang2222** [comment]
Thanks a lot,I have tried in this way,but the prediction results sometimes are  negative while the datas marked as label are always positive,should I deal with the prediction results additionally?

**Comment by ZoeJiang2222** [comment]
> Thanks a lot,I have tried in this way,but the prediction results sometimes are negative while the datas marked as label are always positive,should I deal with the prediction results additionally?

Thanks a lot,I have tried in this way,but the prediction results sometimes are negative while the datas marked as label are always positive,should I deal with the prediction results additionally?

**Comment by ZoeJiang2222** [comment]
> Thanks a lot,I have tried in this way,but the prediction results sometimes are negative while the datas marked as label are always positive,should I deal with the prediction results additionally?

**Comment by ZoeJiang2222** [comment]
Thank you very much!!!
