### ISSUE TITLE
How to predict with self-defined configurations?

### ISSUE THREAD

**Issue by ZoeJiang2222** [knowledgedefinednetworking/demo-routenet#24]
Hello,
now I can use your source code and datasets to get accurate predictions, but I want to know how can I use the model to predict with self-defined configurations?Or specificly, how can I build my own datasets?
Thank you very much.

**Comment by paulalmasan** [comment]
Hello,
To build your own datasets you need to execute a network simulator. The source code of our network simulator is not open source yet but in the following link you can find a collection of datasets that may be interesting for you:
https://github.com/BNN-UPC/NetworkModelingDatasets
Best,
Paul

**Comment by ZoeJiang2222** [comment]
Thank you  very much!
