### ISSUE TITLE
Can not install tensorflow-gpu 1.14.0 from requirements.txt?

### ISSUE THREAD

**Issue by PolynomialDivision** [knowledgedefinednetworking/demo-routenet#5]
Are the software versions fixed for this challenge? I can not install it on Manjaro 5.7.0-3.

> ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.14.0 (from -r requirements.txt (line 20)) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0)
ERROR: No matching distribution found for tensorflow-gpu==1.14.0 (from -r requirements.txt (line 20))

**Comment by jsuarezv** [comment]
Hello, 
Please, instead of using "tensorflow-gpu", try to install:
tensorflow==1.14.0
Also, if you prefer, we provide a newer implementation in TensorFlow 2.1 at the following repository:
https://github.com/knowledgedefinednetworking/RouteNet-challenge

**Comment by PolynomialDivision** [comment]
> Hello,
> Please, instead of using "tensorflow-gpu", try to install:
> tensorflow==1.14.0
> Also, if you prefer, we provide a newer implementation in TensorFlow 2.1 at the following repository:
> https://github.com/knowledgedefinednetworking/RouteNet-challenge

Works. Thanks! Will close.
